### ISSUE TITLE
Installation message

### ISSUE THREAD

**Issue by alain01** [XoopsModulesArchive/rssfit#6]
Incorrect integer value: '' for column 'misc_id' at row 1
INSERT INTO x007_rssfit_misc VALUES ('', 'channel', 'title', 'XOOPS Site', ''), ('', 'channel', 'link', 'http://localhost', ''), ('', 'channel', 'description', 'Just Use it!', ''), ('', 'channel', 'copyright', '', ''), ('', 'channel', 'managingEditor', 'mymail@dot.com (XOOPS Site)', ''), ('', 'channel', 'webMaster', 'mymail@dot.com (XOOPS Site)', ''), ('', 'channel', 'category', '', ''), ('', 'channel', 'generator', 'XOOPS 2.5.9 / RSSFit 1.30', ''), ('', 'channel', 'docs', 'http://blogs.law.harvard.edu/tech/rss', ''), ('', 'channelimg', 'url', 'http://localhost/images/logo.gif', ''), ('', 'channelimg', 'title', 'XOOPS Site', ''), ('', 'channelimg', 'link', 'http://localhost', '');

**Comment by mambax7** [comment]
Should be fixed now...
Before Richard approves here, you can test it from: https://github.com/mambax7/rssfit
